# Generated by Django 4.2.10 on 2025-04-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
